//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Baden-Baden (2953504)")]
        public string cityID {
            get {
                return ((string)(this["cityID"]));
            }
            set {
                this["cityID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Baden-Baden (2953504)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection cityIDBookmarks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cityIDBookmarks"]));
            }
            set {
                this["cityIDBookmarks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string apikey {
            get {
                return ((string)(this["apikey"]));
            }
            set {
                this["apikey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Celsius")]
        public string setTempUnit {
            get {
                return ((string)(this["setTempUnit"]));
            }
            set {
                this["setTempUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m/s")]
        public string setWindSpeedUnit {
            get {
                return ((string)(this["setWindSpeedUnit"]));
            }
            set {
                this["setWindSpeedUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<current><city id=""2643743"" name=""London""><coord lon=""-0.13"" lat=""51.51""/><country>GB</country><sun rise=""2016-05-24T03:55:25"" set=""2016-05-24T20:00:22""/></city><temperature value=""283.36"" min=""281.15"" max=""286.85"" unit=""kelvin""/><humidity value=""66"" unit=""%""/><pressure value=""1020"" unit=""hPa""/><wind><speed value=""5.1"" name=""Gentle Breeze""/><gusts/><direction value=""30"" code=""NNE"" name=""North-northeast""/></wind><clouds value=""0"" name=""clear sky""/><visibility/><precipitation mode=""no""/><weather number=""800"" value=""clear sky"" icon=""01n""/><lastupdate value=""2016-05-24T21:34:09""/></current>")]
        public string currentXml {
            get {
                return ((string)(this["currentXml"]));
            }
            set {
                this["currentXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<weatherdata><location><name>London</name><type/><country>GB</country><timezone/>" +
            "<location altitude=\"0\" latitude=\"51.50853\" longitude=\"-0.12574\" geobase=\"geoname" +
            "s\" geobaseid=\"0\"/></location><credit/><meta><lastupdate/><calctime>0.0147</calct" +
            "ime><nextupdate/></meta><sun rise=\"2016-05-24T03:55:22\" set=\"2016-05-24T20:00:23" +
            "\"/><forecast><time from=\"2016-05-24T21:00:00\" to=\"2016-05-25T00:00:00\"><symbol n" +
            "umber=\"802\" name=\"scattered clouds\" var=\"03n\"/><precipitation/><windDirection de" +
            "g=\"30.0002\" code=\"NNE\" name=\"North-northeast\"/><windSpeed mps=\"4.46\" name=\"Gentl" +
            "e Breeze\"/><temperature unit=\"celsius\" value=\"7.12\" min=\"7.12\" max=\"7.83\"/><pres" +
            "sure unit=\"hPa\" value=\"1022.76\"/><humidity value=\"72\" unit=\"%\"/><clouds value=\"s" +
            "cattered clouds\" all=\"32\" unit=\"%\"/></time><time from=\"2016-05-25T00:00:00\" to=\"" +
            "2016-05-25T03:00:00\"><symbol number=\"500\" name=\"light rain\" var=\"10n\"/><precipit" +
            "ation unit=\"3h\" value=\"0.035\" type=\"rain\"/><windDirection deg=\"14.5026\" code=\"NN" +
            "E\" name=\"North-northeast\"/><windSpeed mps=\"3.68\" name=\"Gentle Breeze\"/><temperat" +
            "ure unit=\"celsius\" value=\"6.68\" min=\"6.68\" max=\"7.36\"/><pressure unit=\"hPa\" valu" +
            "e=\"1021.26\"/><humidity value=\"82\" unit=\"%\"/><clouds value=\"broken clouds\" all=\"6" +
            "4\" unit=\"%\"/></time><time from=\"2016-05-25T03:00:00\" to=\"2016-05-25T06:00:00\"><s" +
            "ymbol number=\"500\" name=\"light rain\" var=\"10d\"/><precipitation unit=\"3h\" value=\"" +
            "0.09\" type=\"rain\"/><windDirection deg=\"11.5008\" code=\"NNE\" name=\"North-northeast" +
            "\"/><windSpeed mps=\"3.41\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value" +
            "=\"8.28\" min=\"8.28\" max=\"8.92\"/><pressure unit=\"hPa\" value=\"1020.43\"/><humidity v" +
            "alue=\"80\" unit=\"%\"/><clouds value=\"overcast clouds\" all=\"88\" unit=\"%\"/></time><t" +
            "ime from=\"2016-05-25T06:00:00\" to=\"2016-05-25T09:00:00\"><symbol number=\"500\" nam" +
            "e=\"light rain\" var=\"10d\"/><precipitation unit=\"3h\" value=\"0.105\" type=\"rain\"/><w" +
            "indDirection deg=\"24.0018\" code=\"NNE\" name=\"North-northeast\"/><windSpeed mps=\"3." +
            "51\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"10.9\" min=\"10.9\" ma" +
            "x=\"11.5\"/><pressure unit=\"hPa\" value=\"1019.95\"/><humidity value=\"75\" unit=\"%\"/><" +
            "clouds value=\"broken clouds\" all=\"80\" unit=\"%\"/></time><time from=\"2016-05-25T09" +
            ":00:00\" to=\"2016-05-25T12:00:00\"><symbol number=\"500\" name=\"light rain\" var=\"10d" +
            "\"/><precipitation unit=\"3h\" value=\"0.005\" type=\"rain\"/><windDirection deg=\"20.00" +
            "09\" code=\"NNE\" name=\"North-northeast\"/><windSpeed mps=\"3.21\" name=\"Light breeze\"" +
            "/><temperature unit=\"celsius\" value=\"12.91\" min=\"12.91\" max=\"13.48\"/><pressure u" +
            "nit=\"hPa\" value=\"1018.63\"/><humidity value=\"76\" unit=\"%\"/><clouds value=\"broken " +
            "clouds\" all=\"76\" unit=\"%\"/></time><time from=\"2016-05-25T12:00:00\" to=\"2016-05-2" +
            "5T15:00:00\"><symbol number=\"500\" name=\"light rain\" var=\"10d\"/><precipitation uni" +
            "t=\"3h\" value=\"0.005\" type=\"rain\"/><windDirection deg=\"15.0033\" code=\"NNE\" name=\"" +
            "North-northeast\"/><windSpeed mps=\"3.21\" name=\"Light breeze\"/><temperature unit=\"" +
            "celsius\" value=\"13.77\" min=\"13.77\" max=\"14.3\"/><pressure unit=\"hPa\" value=\"1017." +
            "78\"/><humidity value=\"72\" unit=\"%\"/><clouds value=\"broken clouds\" all=\"80\" unit=" +
            "\"%\"/></time><time from=\"2016-05-25T15:00:00\" to=\"2016-05-25T18:00:00\"><symbol nu" +
            "mber=\"804\" name=\"overcast clouds\" var=\"04d\"/><precipitation/><windDirection deg=" +
            "\"3.00018\" code=\"N\" name=\"North\"/><windSpeed mps=\"2.51\" name=\"Light breeze\"/><tem" +
            "perature unit=\"celsius\" value=\"13.58\" min=\"13.58\" max=\"14.07\"/><pressure unit=\"h" +
            "Pa\" value=\"1017.68\"/><humidity value=\"69\" unit=\"%\"/><clouds value=\"overcast clou" +
            "ds\" all=\"88\" unit=\"%\"/></time><time from=\"2016-05-25T18:00:00\" to=\"2016-05-25T21" +
            ":00:00\"><symbol number=\"803\" name=\"broken clouds\" var=\"04n\"/><precipitation/><wi" +
            "ndDirection deg=\"335.001\" code=\"NNW\" name=\"North-northwest\"/><windSpeed mps=\"1.9" +
            "7\" name=\"Light breeze\"/><temperature unit=\"celsius\" value=\"12.06\" min=\"12.06\" ma" +
            "x=\"12.51\"/><pressure unit=\"hPa\" value=\"1017.89\"/><humidity value=\"68\" unit=\"%\"/>" +
            "<clouds value=\"broken clouds\" all=\"56\" unit=\"%\"/></time><time from=\"2016-05-25T2" +
            "1:00:00\" to=\"2016-05-26T00:00:00\"><symbol number=\"802\" name=\"scattered clouds\" v" +
            "ar=\"03n\"/><precipitation/><windDirection deg=\"319.008\" code=\"NW\" name=\"Northwest" +
            "\"/><windSpeed mps=\"2.03\" name=\"Light breeze\"/><temperature unit=\"celsius\" value=" +
            "\"8.57\" min=\"8.57\" max=\"8.99\"/><pressure unit=\"hPa\" value=\"1018.1\"/><humidity val" +
            "ue=\"89\" unit=\"%\"/><clouds value=\"scattered clouds\" all=\"36\" unit=\"%\"/></time><ti" +
            "me from=\"2016-05-26T00:00:00\" to=\"2016-05-26T03:00:00\"><symbol number=\"802\" name" +
            "=\"scattered clouds\" var=\"03n\"/><precipitation/><windDirection deg=\"277.001\" code" +
            "=\"W\" name=\"West\"/><windSpeed mps=\"1.26\" name=\"Calm\"/><temperature unit=\"celsius\"" +
            " value=\"6.32\" min=\"6.32\" max=\"6.7\"/><pressure unit=\"hPa\" value=\"1018.21\"/><humid" +
            "ity value=\"93\" unit=\"%\"/><clouds value=\"scattered clouds\" all=\"36\" unit=\"%\"/></t" +
            "ime><time from=\"2016-05-26T03:00:00\" to=\"2016-05-26T06:00:00\"><symbol number=\"80" +
            "2\" name=\"scattered clouds\" var=\"03d\"/><precipitation/><windDirection deg=\"262.50" +
            "6\" code=\"W\" name=\"West\"/><windSpeed mps=\"1.23\" name=\"Calm\"/><temperature unit=\"c" +
            "elsius\" value=\"8.8\" min=\"8.8\" max=\"9.14\"/><pressure unit=\"hPa\" value=\"1018.5\"/><" +
            "humidity value=\"88\" unit=\"%\"/><clouds value=\"scattered clouds\" all=\"36\" unit=\"%\"" +
            "/></time><time from=\"2016-05-26T06:00:00\" to=\"2016-05-26T09:00:00\"><symbol numbe" +
            "r=\"802\" name=\"scattered clouds\" var=\"03d\"/><precipitation/><windDirection deg=\"1" +
            "90.005\" code=\"S\" name=\"South\"/><windSpeed mps=\"1.91\" name=\"Light breeze\"/><tempe" +
            "rature unit=\"celsius\" value=\"14.13\" min=\"14.13\" max=\"14.43\"/><pressure unit=\"hPa" +
            "\" value=\"1018.97\"/><humidity value=\"86\" unit=\"%\"/><clouds value=\"scattered cloud" +
            "s\" all=\"32\" unit=\"%\"/></time><time from=\"2016-05-26T09:00:00\" to=\"2016-05-26T12:" +
            "00:00\"><symbol number=\"802\" name=\"scattered clouds\" var=\"03d\"/><precipitation/><" +
            "windDirection deg=\"193\" code=\"SSW\" name=\"South-southwest\"/><windSpeed mps=\"2.58\"" +
            " name=\"Light breeze\"/><temperature unit=\"celsius\" value=\"16.61\" min=\"16.61\" max=" +
            "\"16.88\"/><pressure unit=\"hPa\" value=\"1019.36\"/><humidity value=\"80\" unit=\"%\"/><c" +
            "louds value=\"scattered clouds\" all=\"44\" unit=\"%\"/></time><time from=\"2016-05-26T" +
            "12:00:00\" to=\"2016-05-26T15:00:00\"><symbol number=\"800\" name=\"clear sky\" var=\"01" +
            "d\"/><precipitation/><windDirection deg=\"174.002\" code=\"S\" name=\"South\"/><windSpe" +
            "ed mps=\"1.98\" name=\"Light breeze\"/><temperature unit=\"celsius\" value=\"18.58\" min" +
            "=\"18.58\" max=\"18.81\"/><pressure unit=\"hPa\" value=\"1018.9\"/><humidity value=\"74\" " +
            "unit=\"%\"/><clouds value=\"clear sky\" all=\"0\" unit=\"%\"/></time><time from=\"2016-05" +
            "-26T15:00:00\" to=\"2016-05-26T18:00:00\"><symbol number=\"800\" name=\"clear sky\" var" +
            "=\"02d\"/><precipitation/><windDirection deg=\"158.508\" code=\"SSE\" name=\"South-sout" +
            "heast\"/><windSpeed mps=\"2.1\" name=\"Light breeze\"/><temperature unit=\"celsius\" va" +
            "lue=\"18.65\" min=\"18.65\" max=\"18.84\"/><pressure unit=\"hPa\" value=\"1018.9\"/><humid" +
            "ity value=\"61\" unit=\"%\"/><clouds value=\"clear sky\" all=\"8\" unit=\"%\"/></time><tim" +
            "e from=\"2016-05-26T18:00:00\" to=\"2016-05-26T21:00:00\"><symbol number=\"801\" name=" +
            "\"few clouds\" var=\"02n\"/><precipitation/><windDirection deg=\"156.006\" code=\"SSE\" " +
            "name=\"South-southeast\"/><windSpeed mps=\"1.91\" name=\"Light breeze\"/><temperature " +
            "unit=\"celsius\" value=\"14.27\" min=\"14.27\" max=\"14.42\"/><pressure unit=\"hPa\" value" +
            "=\"1019.95\"/><humidity value=\"67\" unit=\"%\"/><clouds value=\"few clouds\" all=\"20\" u" +
            "nit=\"%\"/></time><time from=\"2016-05-26T21:00:00\" to=\"2016-05-27T00:00:00\"><symbo" +
            "l number=\"500\" name=\"light rain\" var=\"10n\"/><precipitation unit=\"3h\" value=\"0.19" +
            "\" type=\"rain\"/><windDirection deg=\"139.512\" code=\"SE\" name=\"SouthEast\"/><windSpe" +
            "ed mps=\"1.71\" name=\"Light breeze\"/><temperature unit=\"celsius\" value=\"12.13\" min" +
            "=\"12.13\" max=\"12.24\"/><pressure unit=\"hPa\" value=\"1020.78\"/><humidity value=\"85\"" +
            " unit=\"%\"/><clouds value=\"overcast clouds\" all=\"92\" unit=\"%\"/></time><time from=" +
            "\"2016-05-27T00:00:00\" to=\"2016-05-27T03:00:00\"><symbol number=\"500\" name=\"light " +
            "rain\" var=\"10n\"/><precipitation unit=\"3h\" value=\"2.35\" type=\"rain\"/><windDirecti" +
            "on deg=\"105.501\" code=\"ESE\" name=\"East-southeast\"/><windSpeed mps=\"2.67\" name=\"L" +
            "ight breeze\"/><temperature unit=\"celsius\" value=\"11.88\" min=\"11.88\" max=\"11.95\"/" +
            "><pressure unit=\"hPa\" value=\"1021.37\"/><humidity value=\"97\" unit=\"%\"/><clouds va" +
            "lue=\"overcast clouds\" all=\"100\" unit=\"%\"/></time><time from=\"2016-05-27T03:00:00" +
            "\" to=\"2016-05-27T06:00:00\"><symbol number=\"501\" name=\"moderate rain\" var=\"10d\"/>" +
            "<precipitation unit=\"3h\" value=\"4.97\" type=\"rain\"/><windDirection deg=\"67.5011\" " +
            "code=\"ENE\" name=\"East-northeast\"/><windSpeed mps=\"2.9\" name=\"Light breeze\"/><tem" +
            "perature unit=\"celsius\" value=\"11.34\" min=\"11.34\" max=\"11.38\"/><pressure unit=\"h" +
            "Pa\" value=\"1022.14\"/><humidity value=\"100\" unit=\"%\"/><clouds value=\"overcast clo" +
            "uds\" all=\"100\" unit=\"%\"/></time><time from=\"2016-05-27T06:00:00\" to=\"2016-05-27T" +
            "09:00:00\"><symbol number=\"500\" name=\"light rain\" var=\"10d\"/><precipitation unit=" +
            "\"3h\" value=\"1.67\" type=\"rain\"/><windDirection deg=\"51\" code=\"NE\" name=\"NorthEast" +
            "\"/><windSpeed mps=\"3.81\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value" +
            "=\"12.15\" min=\"12.15\" max=\"12.15\"/><pressure unit=\"hPa\" value=\"1022.66\"/><humidit" +
            "y value=\"97\" unit=\"%\"/><clouds value=\"overcast clouds\" all=\"92\" unit=\"%\"/></time" +
            "><time from=\"2016-05-27T09:00:00\" to=\"2016-05-27T12:00:00\"><symbol number=\"500\" " +
            "name=\"light rain\" var=\"10d\"/><precipitation unit=\"3h\" value=\"0.41\" type=\"rain\"/>" +
            "<windDirection deg=\"72.0129\" code=\"ENE\" name=\"East-northeast\"/><windSpeed mps=\"3" +
            ".6\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"15.81\" min=\"15.81\" " +
            "max=\"15.81\"/><pressure unit=\"hPa\" value=\"1023.2\"/><humidity value=\"95\" unit=\"%\"/" +
            "><clouds value=\"overcast clouds\" all=\"92\" unit=\"%\"/></time><time from=\"2016-05-2" +
            "7T12:00:00\" to=\"2016-05-27T15:00:00\"><symbol number=\"803\" name=\"broken clouds\" v" +
            "ar=\"04d\"/><precipitation/><windDirection deg=\"95.0004\" code=\"E\" name=\"East\"/><wi" +
            "ndSpeed mps=\"3.85\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"17.7" +
            "4\" min=\"17.74\" max=\"17.74\"/><pressure unit=\"hPa\" value=\"1022.96\"/><humidity valu" +
            "e=\"86\" unit=\"%\"/><clouds value=\"broken clouds\" all=\"64\" unit=\"%\"/></time><time f" +
            "rom=\"2016-05-27T15:00:00\" to=\"2016-05-27T18:00:00\"><symbol number=\"801\" name=\"fe" +
            "w clouds\" var=\"02d\"/><precipitation/><windDirection deg=\"101.503\" code=\"ESE\" nam" +
            "e=\"East-southeast\"/><windSpeed mps=\"3.01\" name=\"Light breeze\"/><temperature unit" +
            "=\"celsius\" value=\"17.61\" min=\"17.61\" max=\"17.61\"/><pressure unit=\"hPa\" value=\"10" +
            "22.98\"/><humidity value=\"84\" unit=\"%\"/><clouds value=\"few clouds\" all=\"12\" unit=" +
            "\"%\"/></time><time from=\"2016-05-27T18:00:00\" to=\"2016-05-27T21:00:00\"><symbol nu" +
            "mber=\"801\" name=\"few clouds\" var=\"02n\"/><precipitation/><windDirection deg=\"94.0" +
            "018\" code=\"E\" name=\"East\"/><windSpeed mps=\"2.64\" name=\"Light breeze\"/><temperatu" +
            "re unit=\"celsius\" value=\"13.12\" min=\"13.12\" max=\"13.12\"/><pressure unit=\"hPa\" va" +
            "lue=\"1023.91\"/><humidity value=\"80\" unit=\"%\"/><clouds value=\"few clouds\" all=\"12" +
            "\" unit=\"%\"/></time><time from=\"2016-05-27T21:00:00\" to=\"2016-05-28T00:00:00\"><sy" +
            "mbol number=\"800\" name=\"clear sky\" var=\"01n\"/><precipitation/><windDirection deg" +
            "=\"42.5005\" code=\"NE\" name=\"NorthEast\"/><windSpeed mps=\"3.3\" name=\"Light breeze\"/" +
            "><temperature unit=\"celsius\" value=\"10.47\" min=\"10.47\" max=\"10.47\"/><pressure un" +
            "it=\"hPa\" value=\"1024.29\"/><humidity value=\"81\" unit=\"%\"/><clouds value=\"clear sk" +
            "y\" all=\"0\" unit=\"%\"/></time><time from=\"2016-05-28T00:00:00\" to=\"2016-05-28T03:0" +
            "0:00\"><symbol number=\"802\" name=\"scattered clouds\" var=\"03n\"/><precipitation/><w" +
            "indDirection deg=\"41.0039\" code=\"NE\" name=\"NorthEast\"/><windSpeed mps=\"4.07\" nam" +
            "e=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"9.33\" min=\"9.33\" max=\"9.33" +
            "\"/><pressure unit=\"hPa\" value=\"1023.62\"/><humidity value=\"89\" unit=\"%\"/><clouds " +
            "value=\"scattered clouds\" all=\"36\" unit=\"%\"/></time><time from=\"2016-05-28T03:00:" +
            "00\" to=\"2016-05-28T06:00:00\"><symbol number=\"500\" name=\"light rain\" var=\"10d\"/><" +
            "precipitation unit=\"3h\" value=\"0.01\" type=\"rain\"/><windDirection deg=\"43.5068\" c" +
            "ode=\"NE\" name=\"NorthEast\"/><windSpeed mps=\"3.7\" name=\"Gentle Breeze\"/><temperatu" +
            "re unit=\"celsius\" value=\"9.87\" min=\"9.87\" max=\"9.87\"/><pressure unit=\"hPa\" value" +
            "=\"1023\"/><humidity value=\"95\" unit=\"%\"/><clouds value=\"scattered clouds\" all=\"32" +
            "\" unit=\"%\"/></time><time from=\"2016-05-28T06:00:00\" to=\"2016-05-28T09:00:00\"><sy" +
            "mbol number=\"500\" name=\"light rain\" var=\"10d\"/><precipitation unit=\"3h\" value=\"0" +
            ".02\" type=\"rain\"/><windDirection deg=\"43.0005\" code=\"NE\" name=\"NorthEast\"/><wind" +
            "Speed mps=\"4.21\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"14.26\"" +
            " min=\"14.26\" max=\"14.26\"/><pressure unit=\"hPa\" value=\"1022.27\"/><humidity value=" +
            "\"90\" unit=\"%\"/><clouds value=\"clear sky\" all=\"0\" unit=\"%\"/></time><time from=\"20" +
            "16-05-28T09:00:00\" to=\"2016-05-28T12:00:00\"><symbol number=\"800\" name=\"clear sky" +
            "\" var=\"01d\"/><precipitation/><windDirection deg=\"52.0016\" code=\"NE\" name=\"NorthE" +
            "ast\"/><windSpeed mps=\"4.17\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" va" +
            "lue=\"18.48\" min=\"18.48\" max=\"18.48\"/><pressure unit=\"hPa\" value=\"1020.53\"/><humi" +
            "dity value=\"78\" unit=\"%\"/><clouds value=\"clear sky\" all=\"0\" unit=\"%\"/></time><ti" +
            "me from=\"2016-05-28T12:00:00\" to=\"2016-05-28T15:00:00\"><symbol number=\"800\" name" +
            "=\"clear sky\" var=\"01d\"/><precipitation/><windDirection deg=\"58.5004\" code=\"ENE\" " +
            "name=\"East-northeast\"/><windSpeed mps=\"3.93\" name=\"Gentle Breeze\"/><temperature " +
            "unit=\"celsius\" value=\"20.61\" min=\"20.61\" max=\"20.61\"/><pressure unit=\"hPa\" value" +
            "=\"1018.23\"/><humidity value=\"67\" unit=\"%\"/><clouds value=\"clear sky\" all=\"0\" uni" +
            "t=\"%\"/></time><time from=\"2016-05-28T15:00:00\" to=\"2016-05-28T18:00:00\"><symbol " +
            "number=\"800\" name=\"clear sky\" var=\"02d\"/><precipitation/><windDirection deg=\"75." +
            "501\" code=\"ENE\" name=\"East-northeast\"/><windSpeed mps=\"4.96\" name=\"Gentle Breeze" +
            "\"/><temperature unit=\"celsius\" value=\"19.58\" min=\"19.58\" max=\"19.58\"/><pressure " +
            "unit=\"hPa\" value=\"1017.37\"/><humidity value=\"56\" unit=\"%\"/><clouds value=\"clear " +
            "sky\" all=\"8\" unit=\"%\"/></time><time from=\"2016-05-28T18:00:00\" to=\"2016-05-28T21" +
            ":00:00\"><symbol number=\"800\" name=\"clear sky\" var=\"01n\"/><precipitation/><windDi" +
            "rection deg=\"78.5003\" code=\"ENE\" name=\"East-northeast\"/><windSpeed mps=\"4.99\" na" +
            "me=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"15.27\" min=\"15.27\" max=\"1" +
            "5.27\"/><pressure unit=\"hPa\" value=\"1017.74\"/><humidity value=\"56\" unit=\"%\"/><clo" +
            "uds value=\"clear sky\" all=\"0\" unit=\"%\"/></time><time from=\"2016-05-28T21:00:00\" " +
            "to=\"2016-05-29T00:00:00\"><symbol number=\"800\" name=\"clear sky\" var=\"02n\"/><preci" +
            "pitation/><windDirection deg=\"57\" code=\"ENE\" name=\"East-northeast\"/><windSpeed m" +
            "ps=\"5.03\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"12.75\" min=\"1" +
            "2.75\" max=\"12.75\"/><pressure unit=\"hPa\" value=\"1017.26\"/><humidity value=\"70\" un" +
            "it=\"%\"/><clouds value=\"clear sky\" all=\"8\" unit=\"%\"/></time><time from=\"2016-05-2" +
            "9T00:00:00\" to=\"2016-05-29T03:00:00\"><symbol number=\"801\" name=\"few clouds\" var=" +
            "\"02n\"/><precipitation/><windDirection deg=\"46.5085\" code=\"NE\" name=\"NorthEast\"/>" +
            "<windSpeed mps=\"5.31\" name=\"Gentle Breeze\"/><temperature unit=\"celsius\" value=\"1" +
            "0.99\" min=\"10.99\" max=\"10.99\"/><pressure unit=\"hPa\" value=\"1016.21\"/><humidity v" +
            "alue=\"78\" unit=\"%\"/><clouds value=\"few clouds\" all=\"12\" unit=\"%\"/></time><time f" +
            "rom=\"2016-05-29T03:00:00\" to=\"2016-05-29T06:00:00\"><symbol number=\"802\" name=\"sc" +
            "attered clouds\" var=\"03d\"/><precipitation/><windDirection deg=\"54.0041\" code=\"NE" +
            "\" name=\"NorthEast\"/><windSpeed mps=\"5.26\" name=\"Gentle Breeze\"/><temperature uni" +
            "t=\"celsius\" value=\"12.21\" min=\"12.21\" max=\"12.21\"/><pressure unit=\"hPa\" value=\"1" +
            "016.31\"/><humidity value=\"72\" unit=\"%\"/><clouds value=\"scattered clouds\" all=\"32" +
            "\" unit=\"%\"/></time><time from=\"2016-05-29T06:00:00\" to=\"2016-05-29T09:00:00\"><sy" +
            "mbol number=\"802\" name=\"scattered clouds\" var=\"03d\"/><precipitation/><windDirect" +
            "ion deg=\"64.0013\" code=\"ENE\" name=\"East-northeast\"/><windSpeed mps=\"5.87\" name=\"" +
            "Moderate breeze\"/><temperature unit=\"celsius\" value=\"16.81\" min=\"16.81\" max=\"16." +
            "81\"/><pressure unit=\"hPa\" value=\"1016.44\"/><humidity value=\"70\" unit=\"%\"/><cloud" +
            "s value=\"scattered clouds\" all=\"44\" unit=\"%\"/></time><time from=\"2016-05-29T09:0" +
            "0:00\" to=\"2016-05-29T12:00:00\"><symbol number=\"804\" name=\"overcast clouds\" var=\"" +
            "04d\"/><precipitation/><windDirection deg=\"60.5033\" code=\"ENE\" name=\"East-northea" +
            "st\"/><windSpeed mps=\"5.55\" name=\"Moderate breeze\"/><temperature unit=\"celsius\" v" +
            "alue=\"18.53\" min=\"18.53\" max=\"18.53\"/><pressure unit=\"hPa\" value=\"1016.04\"/><hum" +
            "idity value=\"62\" unit=\"%\"/><clouds value=\"overcast clouds\" all=\"88\" unit=\"%\"/></" +
            "time><time from=\"2016-05-29T12:00:00\" to=\"2016-05-29T15:00:00\"><symbol number=\"8" +
            "03\" name=\"broken clouds\" var=\"04d\"/><precipitation/><windDirection deg=\"55.0001\"" +
            " code=\"NE\" name=\"NorthEast\"/><windSpeed mps=\"6.11\" name=\"Moderate breeze\"/><temp" +
            "erature unit=\"celsius\" value=\"19.17\" min=\"19.17\" max=\"19.17\"/><pressure unit=\"hP" +
            "a\" value=\"1016.05\"/><humidity value=\"57\" unit=\"%\"/><clouds value=\"broken clouds\"" +
            " all=\"80\" unit=\"%\"/></time><time from=\"2016-05-29T15:00:00\" to=\"2016-05-29T18:00" +
            ":00\"><symbol number=\"803\" name=\"broken clouds\" var=\"04d\"/><precipitation/><windD" +
            "irection deg=\"38.5009\" code=\"NE\" name=\"NorthEast\"/><windSpeed mps=\"6.31\" name=\"M" +
            "oderate breeze\"/><temperature unit=\"celsius\" value=\"17.89\" min=\"17.89\" max=\"17.8" +
            "9\"/><pressure unit=\"hPa\" value=\"1016.43\"/><humidity value=\"53\" unit=\"%\"/><clouds" +
            " value=\"broken clouds\" all=\"68\" unit=\"%\"/></time><time from=\"2016-05-29T18:00:00" +
            "\" to=\"2016-05-29T21:00:00\"><symbol number=\"802\" name=\"scattered clouds\" var=\"03n" +
            "\"/><precipitation/><windDirection deg=\"28.0013\" code=\"NNE\" name=\"North-northeast" +
            "\"/><windSpeed mps=\"5.56\" name=\"Moderate breeze\"/><temperature unit=\"celsius\" val" +
            "ue=\"14.87\" min=\"14.87\" max=\"14.87\"/><pressure unit=\"hPa\" value=\"1017.57\"/><humid" +
            "ity value=\"55\" unit=\"%\"/><clouds value=\"scattered clouds\" all=\"48\" unit=\"%\"/></t" +
            "ime></forecast></weatherdata>")]
        public string forecastXml {
            get {
                return ((string)(this["forecastXml"]));
            }
            set {
                this["forecastXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
    }
}
